### ISSUE TITLE
config.yaml

### ISSUE THREAD

**Issue by wwvvwvwv** [nelvko/clash-for-linux-install#1]
config.yaml文件内应该配置什么信息？

**Comment by nelvko** [comment]
> config.yaml文件内应该配置什么信息？

执行安装脚本后，脚本会提示输入机场订阅链接进行下载。
如果下载失败则另有提示，可以试下在浏览器中打开订阅链接，会自动下载一个配置文件，把文件内容粘贴到 config.yaml 文件里，然后重新执行install.sh 便可使用 clash 了。
之前试过挺多安装脚本都是因为无法访问订阅链接导致无法完成后续安装，所以编写了此脚本，多了一种解决方案。

**Comment by wwvvwvwv** [comment]
> > config.yaml文件内应该配置什么信息？
> 
> 执行安装脚本后，脚本会提示输入机场订阅链接进行下载。 如果下载失败则另有提示，可以试下在浏览器中打开订阅链接，会自动下载一个配置文件，把文件内容粘贴到 config.yaml 文件里，然后重新执行install.sh 便可使用 clash 了。 之前试过挺多安装脚本都是因为无法访问订阅链接导致无法完成后续安装，所以编写了此脚本，多了一种解决方案。

您好，现在我成功安装了clash但是启动会报错，下面是日志信息：
Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ clash: 19:15:19 FTL [Config] parse config failed error=yaml: line 90: mapping values are not allowed in this context
Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: clash.service: main process exited, code=exited, status=255/n/a
Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: Unit clash.service entered failed state.
Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: clash.service failed.
Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: clash.service holdoff time over, scheduling restart.
Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: Stopped Clash 守护进程, Go 语言实现的基于规则的代理..
Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: start request repeated too quickly for clash.service
Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: Failed to start Clash 守护进程, Go 语言实现的基于规则的代理..
Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: Unit clash.service entered failed state.
Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: clash.service failed.

这里是90行及附近
![Snipaste_2024-03-02_15-58-32](https://github.com/nelvko/clash-for-linux-install/assets/134823482/50fc64b8-3327-4a6c-a31f-53e2517e11bf)

**Comment by nelvko** [comment]
> > > config.yaml文件内应该配置什么信息？
> 
> > 
> 
> > 执行安装脚本后，脚本会提示输入机场订阅链接进行下载。 如果下载失败则另有提示，可以试下在浏览器中打开订阅链接，会自动下载一个配置文件，把文件内容粘贴到 config.yaml 文件里，然后重新执行install.sh 便可使用 clash 了。 之前试过挺多安装脚本都是因为无法访问订阅链接导致无法完成后续安装，所以编写了此脚本，多了一种解决方案。
> 
> 
> 
> 您好，现在我成功安装了clash但是启动会报错，下面是日志信息：
> 
> Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ clash: 19:15:19 FTL [Config] parse config failed error=yaml: line 90: mapping values are not allowed in this context
> 
> Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: clash.service: main process exited, code=exited, status=255/n/a
> 
> Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: Unit clash.service entered failed state.
> 
> Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: clash.service failed.
> 
> Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: clash.service holdoff time over, scheduling restart.
> 
> Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: Stopped Clash 守护进程, Go 语言实现的基于规则的代理..
> 
> Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: start request repeated too quickly for clash.service
> 
> Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: Failed to start Clash 守护进程, Go 语言实现的基于规则的代理..
> 
> Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: Unit clash.service entered failed state.
> 
> Apr 19 19:15:19 iZ2zeeygotvs3igx2rtukyZ systemd: clash.service failed.
> 
> 
> 
> 这里是90行及附近
> 
> ![image](https://github.com/nelvko/clash-for-linux-install/assets/134823482/99ebcc92-314b-4f9e-8c21-00164d13b412)
> 
> 
> 
> 
> 
> 

订阅链接是需要去机场购买的，不是文档中的代理加速链接

**Comment by wwvvwvwv** [comment]
您好那个链接应该在哪里找到呀，clash官方吗 @nelvko

**Comment by nelvko** [comment]
> 您好那个链接应该在哪里找到呀，clash官方吗 @nelvko 

https://次元.net/auth/register?code=oUbI
这个是我小伙伴目前在用的，还不错，可以试下

**Comment by huoyufeiqaq** [comment]
我部署后，但是还是不可以访问外网
![image](https://github.com/user-attachments/assets/2ceee52c-a7cc-44fb-84b6-2c5576a52340)

**Comment by nelvko** [comment]
> 我部署后，但是还是不可以访问外网 ![image](https://private-user-images.githubusercontent.com/112455226/392273704-2ceee52c-a7cc-44fb-84b6-2c5576a52340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyOTg1ODksIm5iZiI6MTczMzI5ODI4OSwicGF0aCI6Ii8xMTI0NTUyMjYvMzkyMjczNzA0LTJjZWVlNTJjLWE3Y2MtNDRmYi04NGI2LTJjNTU3NmE1MjM0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwNzQ0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWZkYTE1MWRjZmJhN2FkNzJmZjYxZTM2YjllNjY3OGVkMmNhZGYxOWMyMzVjZjljNDdlMTgyYjRjMzQ4Y2Q5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qV2abYuOW4brzOivoUuYYkAx9dEu2vzWp6vg_j80y3Y)

- 进web面板，看下有没有选direct的地方，direct是直连不走代理
- 打印下代理变量看有没有值 `echo $http_proxy`

**Comment by Yawnaa** [comment]
订阅连接如何自动下载配置文件呢？
我的订阅连接只有一串url地址

**Comment by nelvko** [comment]
> 订阅连接如何自动下载配置文件呢？
> 
> 我的订阅连接只有一串url地址

用浏览器打开订阅链接会自动下载配置文件或显示出来

**Comment by Yawnaa** [comment]
你好，粘贴我自己的订阅地址后，显示"下载失败或配置无效,自行粘贴配置的配置文件" 是下载到什么位置了，没有找到

**Comment by Yawnaa** [comment]
感谢，但是粘贴进去后，还是显示“下载失败或配置失效，请粘贴···”是什么原因

**Comment by nelvko** [comment]
> 感谢，但是粘贴进去后，还是显示“下载失败或配置失效，请粘贴···”是什么原因

README 文档中常见问题里有解决方法

**Comment by nelvko** [comment]
> 感谢，但是粘贴进去后，还是显示“下载失败或配置失效，请粘贴···”是什么原因

已修复，重新克隆项目试下

**Comment by hearwish** [comment]
大佬请问如何选择节点，公网这个地址https://clash.razord.top 是控制clash的吗，如何配置呢

**Comment by nelvko** [comment]
> 大佬请问如何选择节点，公网这个地址https://clash.razord.top 是控制clash的吗，如何配置呢

执行clashui会打印两个控制台地址，均需要放开端口才能访问（默认是9090）。
- 域名地址的是公共的部署在别人服务器上的，你可以输入你的ip、端口，密钥登录后控制你服务器上的clash。
- 公网ip的地址的是部署在你服务器上的控制台，如果没配置密钥的话可以直接登录。

**Comment by JohntyZhou** [comment]
> > 感谢，但是粘贴进去后，还是显示“下载失败或配置失效，请粘贴···”是什么原因
> 
> 已修复，重新克隆项目试下

Hello, this issue still exists.

**Comment by nelvko** [comment]
> > > 感谢，但是粘贴进去后，还是显示“下载失败或配置失效，请粘贴···”是什么原因
> > 
> > 已修复，重新克隆项目试下
> 
> Hello, this issue still exists.

Please provide a screenshot of the script running.

**Comment by llangosh** [comment]
请问 一键安装的 sinbox clash 配置订阅 如何添加订阅

**Comment by nelvko** [comment]
> 请问 一键安装的 sinbox clash 配置订阅 如何添加订阅

只能安装 clash 或 mihomo 内核，未支持 sing-box 内核。执行安装脚本后会提示填写订阅链接下载配置。
