### ISSUE TITLE
System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is down clash: 启动失败: 执行 "systemctl status clash" 查看日志

### ISSUE THREAD

**Issue by luozhongze** [nelvko/clash-for-linux-install#11]
![微信图片_20241111205707](https://github.com/user-attachments/assets/dc733856-181e-41ef-b719-a00fd18d7529)

**Comment by luozhongze** [comment]
还有就是我clashon之后，是这样
(base) root@8efe5851255d:~/lzz/clash-for-linux-install# clashon
bash: clashon: command not found

**Comment by nelvko** [comment]
提供下系统版本

**Comment by luozhongze** [comment]
Linux 8efe5851255d 5.15.0-91-generic #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nelvko** [comment]
是使用 WSL 安装的吗？WSL尚未支持systemd，详见：https://askubuntu.com/questions/1379425/system-has-not-been-booted-with-systemd-as-init-system-pid-1-cant-operate
这个脚本是使用 `systemctl` 来管理服务的，你可以把脚本中关于`systemctl`的命令改为`service`的，详见：https://www.cnblogs.com/a5idc/p/13752839.html
