### ISSUE TITLE
clashon/clashoff未写入source文件，终端关闭后服务无法启动，clashon提示clashon: command not found

### ISSUE THREAD

**Issue by ponyme** [nelvko/clash-for-linux-install#12]
**系统 & 版本号：**

**描述 & 复现：**

**截图：**

**Comment by nelvko** [comment]
系统和 shell 环境发下

**Comment by ponyme** [comment]
Linux version 6.8.0-48-generic (buildd@lcy02-amd64-010) (x86_64-linux-gnu-gcc-13 (Ubuntu 13.2.0-23ubuntu4) 13.2.0, GNU ld (GNU Binutils for Ubuntu) 2.42) #48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024

# /etc/shells: valid login shells
/bin/sh
/usr/bin/sh
/bin/bash
/usr/bin/bash
/bin/rbash
/usr/bin/rbash
/usr/bin/dash
/usr/bin/screen
/usr/bin/tmux

感谢及时回复

**Comment by nelvko** [comment]
终端执行 echo $SHELL 或 echo $0 输出什么？

**Comment by ponyme** [comment]
/bin/bash

**Comment by nelvko** [comment]
在项目根路径内，执行 sudo . install.sh 试试

**Comment by ponyme** [comment]
sudo: .: command not found

**Comment by nelvko** [comment]
sudo bash install.sh

**Comment by ponyme** [comment]
我安装时就是使用的这个命令

**Comment by nelvko** [comment]
你应该是用普通用户执行的安装脚本，脚本里有些命令没有权限执行。

**Comment by nelvko** [comment]
在项目根目录下执行sudo bash uninstall.sh，然后再执行sudo bash install.sh，试下是否正常，发下截图

**Comment by ponyme** [comment]
![image](https://github.com/user-attachments/assets/893d37ba-be82-4e81-bb9b-02725331ce25)
现在的情况是，如果使用sudo bash install.sh，在本终端中也无法使用clashon，如果是sudo -s进入root后使用  . install.sh，则在本终端可以使用，终端关闭再打开后又无法使用

**Comment by nelvko** [comment]
因为 bash 运行脚本不对当前 shell 生效，readme 中有说明。当前 shell 执行下 bash 后就可以了，或者你退出终端重新登录下
