### ISSUE TITLE
Arm64环境下的最新版本无法正常使用clash链接GitHub

### ISSUE THREAD

**Issue by Kang2001** [nelvko/clash-for-linux-install#13]
**系统 & 版本号：**
Arm64环境下的最新版本
**描述 & 复现：**
运行安装脚本后，再次无法正常使用和链接到GitHub
![image](https://github.com/user-attachments/assets/ba2e1569-b6ae-4b93-98d5-f2ff4de6295a)

**截图：**
![image](https://github.com/user-attachments/assets/99f0592a-a9d0-4ee0-b665-a86a40425a6b)

**Comment by nelvko** [comment]
使用 `bash install.sh` 安装部署后不会对当前shell生效
当前shell执行下`source /etc/bashrc` 或 `bash` 试下

**Comment by Kang2001** [comment]
已解决

**Comment by nelvko** [comment]
README文档有解释，可以参考下
https://github.com/nelvko/clash-for-linux-install?tab=readme-ov-file#tips

**Comment by Kang2001** [comment]
> README文档有解释，可以参考下 https://github.com/nelvko/clash-for-linux-install?tab=readme-ov-file#tips

好的，谢谢你
