### ISSUE TITLE
❌ 下载失败或配置无效: 请自行粘贴配置内容到 ./resource/config.yaml 后再执行安装脚本

### ISSUE THREAD

**Issue by cyl-ly** [nelvko/clash-for-linux-install#14]
> 请先提供以下信息
```shell
# 系统版本信息
centos8

# 当前所用 shell
echo $0
```

**描述 & 复现：**
后续，用浏览器打开订阅链接，并且将内容复制到config.yaml中，再次执行install.sh，他还是会让我输入订阅链接，重复这个步骤
打开config文件，里面已经是我订阅链接的内容了
**截图：**
![image](https://github.com/user-attachments/assets/cd164883-cd7d-4e24-85a3-5e57cb9d808b)

**Comment by nelvko** [comment]
看下你的配置内容是 yaml格式且是 clash 形式的吗，这是官方参考配置 https://clash.wiki/configuration/configuration-reference.html
这是检查配置是否有效的代码：https://github.com/nelvko/clash-for-linux-install/blob/8a36a90ba653136c53c8fa51327cfcc4bbc41f8f/script/common.sh#L31

**Comment by gralliry** [comment]
> 看下你的配置内容是 yaml格式且是 clash 形式的吗，这是官方参考配置 https://clash.wiki/configuration/configuration-reference.html 这是检查配置是否有效的代码：
> 
> https://github.com/nelvko/clash-for-linux-install/blob/8a36a90ba653136c53c8fa51327cfcc4bbc41f8f/script/common.sh#L31

部分梯子给出的订阅链接返回的是配置内容的base64编码，这可能是配置无效的原因，是否可以增加对于base64内容的检测和解码

**Comment by nelvko** [comment]
会考虑增加，不过我没用过此类订阅，不能实战测试可用性，有兴趣的话可以提 PR

**Comment by gralliry** [comment]
> 看下你的配置内容是 yaml格式且是 clash 形式的吗，这是官方参考配置 https://clash.wiki/configuration/configuration-reference.html 这是检查配置是否有效的代码：
> 
> https://github.com/nelvko/clash-for-linux-install/blob/8a36a90ba653136c53c8fa51327cfcc4bbc41f8f/script/common.sh#L31

某些梯子的订阅链接返回的是配置内容的base64编码

且解码后的配置内容并不是yaml格式而是vmess格式，如：
```
vmess://{这里仍是base64编码后的内容}==

trojan://{id}@{domain}:{port}?params=....
```

这种配置文件放在clash是可以解析和订阅的

### 解决办法

使用clash（或其他）的图形化版本：
![image](https://github.com/user-attachments/assets/ac431840-867c-4dd2-8eeb-873294f6acaf)
直接打开配置文件，里面就是yaml格式的内容，直接复制到`./resource/config.yaml`

**Comment by NirvanafeLis** [comment]
遭遇了相同的问题 且通过上文解决方法复现依旧无法解决

**Comment by nelvko** [comment]
> 遭遇了相同的问题 且通过上文解决方法复现依旧无法解决

确保 config.yaml 内容格式正确，可通过 clash 命令验证：
最新版本执行 install 脚本后会解压 clash 到 resource 目录中，执行`./resource/clash -d resource -t`查看打印结果

**Comment by NirvanafeLis** [comment]
> > 遭遇了相同的问题 且通过上文解决方法复现依旧无法解决
> 
> 确保 config.yaml 内容格式正确，可通过 clash 命令验证： 最新版本执行 install 脚本后会解压 clash 到 resource 目录中，执行`./resource/clash -d resource -t`查看打印结果

![image](https://github.com/user-attachments/assets/2605c397-1333-4b24-8838-e66fc742024b)
验证后回显了格式正确 但依旧失败 网络正常连通 是哪里的问题呢

**Comment by nelvko** [comment]
> 呢

已修复，重新克隆项目试下，之前的 bug 是 clash 命令没加路径执行失败导致误判了

**Comment by nelvko** [comment]
> > > 遭遇了相同的问题 且通过上文解决方法复现依旧无法解决
> 
> > 
> 
> > 确保 config.yaml 内容格式正确，可通过 clash 命令验证： 最新版本执行 install 脚本后会解压 clash 到 resource 目录中，执行`./resource/clash -d resource -t`查看打印结果
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/2605c397-1333-4b24-8838-e66fc742024b)
> 
> 验证后回显了格式正确 但依旧失败 网络正常连通 是哪里的问题呢
> 
> 

已修复，重新克隆项目试下，之前的 bug 是 clash 命令没加路径执行失败导致误判了

**Comment by NirvanafeLis** [comment]
已成功配置 感谢修复

**Comment by yjpzuishuai** [comment]
<img width="1182" height="138" alt="Image" src="https://github.com/user-attachments/assets/165a4415-9cb6-4969-bb13-2f5487e479ef" />
请问这是什么问题导致的
