### ISSUE TITLE
配置看起来成功了，无法连接外网

### ISSUE THREAD

**Issue by ponyme** [nelvko/clash-for-linux-install#15]
# 系统版本信息
ubuntu24.04

# 当前所用 shell
/bin/bash

![image](https://github.com/user-attachments/assets/a5a41b3a-421c-4173-9452-c7753a62e8d0)

![image](https://github.com/user-attachments/assets/178e22b8-458f-45d8-9a86-e57c7626eeea)
连接中始终没有任何新链接
![image](https://github.com/user-attachments/assets/d0a25f00-159f-482e-bed4-5a2cb4a0559e)

**Comment by nelvko** [comment]
日志的error应该是7890端口已被占用了
执行`lsof -i:7890`看是哪个进程占用了

**Comment by ponyme** [comment]
![image](https://github.com/user-attachments/assets/e955b29b-44d8-453b-b8b3-8250fea7d236)

**Comment by ponyme** [comment]
kill掉后成功了，谢谢大佬

**Comment by nelvko** [comment]
你的ssh端口占用了clash的端口了，两种解决方法：
1. 更换ssh端口（推荐）
2. 将所有脚本中的7890替换为未被占用的端口后再安装
