### ISSUE TITLE
放行端口9090后，进不去UI

### ISSUE THREAD

**Issue by LOVEUR** [nelvko/clash-for-linux-install#17]
> 请先提供以下信息
```shell
# 系统版本信息
hostnamectl

# 当前所用 shell
echo $0
```

**描述 & 复现：**

**截图：**

**Comment by LOVEUR** [comment]
eth0: error fetching interface information: Device not found

**Comment by nelvko** [comment]
执行 `ifconfig` 截图看下

**Comment by qyf13505049895** [comment]
![image](https://github.com/user-attachments/assets/c58f887a-c923-4194-9be2-6d3fd894bc18)
我也遇到了这个问题请问解决了吗

**Comment by nelvko** [comment]
@qyf13505049895 你的是无线网卡,内网ip地址是最底下那个103的
截图没打码订阅链接,先帮你删了

**Comment by nelvko** [comment]
已发新版优化, 使用了下列通用命令来获取内网 ip 
```bash
hostname -I | awk '{print $1}'

ip route get 1.1.1.1 | grep -oP 'src \K\S+'
```
