### ISSUE TITLE
脚本无法触发订阅链接配置

### ISSUE THREAD

**Issue by EntID911** [nelvko/clash-for-linux-install#18]
```shell
# 系统版本信息
Ubuntu22.04/24.04

# 当前所用 shell
echo $0

```

**描述 & 复现：**
两台服务器均稳定复现，安装时无法触发配置订阅链接的步骤，直接跳过并且生成了webUI，并结束安装，卸载后仍稳定复现此问题
**截图（勿泄露订阅）：**
![image](https://github.com/user-attachments/assets/b5199c39-991a-41f5-9f87-32a56466d556)

**Comment by nelvko** [comment]
已发新版修复，感谢反馈。原因是 clash 命令校验配置文件时，配置文件不存在会新建，所以检验通过并继续安装了。其实也算部署好了，就是配置里没订阅内容...

**Comment by EntID911** [comment]
> 已发新版修复，感谢反馈。原因是 clash 命令校验配置文件时，配置文件不存在会新建，所以检验通过并继续安装了。其实也算部署好了，就是配置里没订阅内容...

辛苦
