### ISSUE TITLE
配置无效：请检查配置内容

### ISSUE THREAD

**Issue by wenkeming** [nelvko/clash-for-linux-install#19]
> [!CAUTION]
>
> 请先提供以下信息

```shell
# 系统版本信息
Ubuntu 22.04 LTS 

# 当前所用 shell
bash

```

**描述 & 复现：**
输入订阅地址后，配置下载也成功了，但是提示 `❌ 配置无效：请检查配置内容`

**截图（勿泄露订阅）：**
<img width="608" alt="截图" src="https://github.com/user-attachments/assets/671e89d3-13d6-4ba8-9b33-9782986dec66" />

**Comment by nelvko** [comment]
参考下这个：https://github.com/nelvko/clash-for-linux-install/issues/14#issuecomment-2513303276

**Comment by wenkeming** [comment]
> 参考下这个：[#14 (comment)](https://github.com/nelvko/clash-for-linux-install/issues/14#issuecomment-2513303276)

收到，感谢。试了下，确实是加密的，还是vmess的。。。

**Comment by wenkeming** [comment]
搞定了，再次感谢！

**Comment by nelvko** [comment]
已支持本地订阅转换
