### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by wwvvwvwv** [nelvko/clash-for-linux-install#2]
现在我成功完成配置并启动，但还是无法访问外网
![image](https://github.com/nelvko/clash-for-linux-install/assets/134823482/b2eb6fba-8fc0-4612-80d3-455690f8c009)

**Comment by nelvko** [comment]
> 现在我成功完成配置并启动，但还是无法访问外网
> 
> ![image](https://github.com/nelvko/clash-for-linux-install/assets/134823482/b2eb6fba-8fc0-4612-80d3-455690f8c009)
> 
> 

试下 curl -sSL www.google.com ，ping 好像不走代理

**Comment by wwvvwvwv** [comment]
> > 现在我成功完成配置并启动，但还是无法访问外网
> > ![图像](https://private-user-images.githubusercontent.com/134823482/324152782-b2eb6fba-8fc0-4612-80d3-455690f8c009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1ODY3ODksIm5iZiI6MTcxMzU4NjQ4OSwicGF0aCI6Ii8xMzQ4MjM0ODIvMzI0MTUyNzgyLWIyZWI2ZmJhLThmYzAtNDYxMi04MGQzLTQ1NTY5MGY4YzAwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQwNDE0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGY2NTg5NDE4NWQ2MzBjOGJkNTU1NjY2MGJhZTBiNWJmMzI1MjYyNTVhYWU3YTk3OTY2MWI0ODRkN2JmZjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9RbU7kC9OS9TAhQMClAfngC1pI6Hpm77I3h57ZV0svI)
> 
> 试下curl -sSL [www.google.com](http://www.google.com)，ping 希望不走代理

![image](https://github.com/nelvko/clash-for-linux-install/assets/134823482/69ef96ad-a11f-4794-bad6-1dfcc649aa52)
依旧无法成功

**Comment by nelvko** [comment]
执行第一条命令打印下日志
执行第二条命令，如果终端输出一堆代码说明连通外网了
```
systemctl status clash
curl -sSL google.com
```

**Comment by wwvvwvwv** [comment]
查看日志：
![image](https://github.com/nelvko/clash-for-linux-install/assets/134823482/60e8ce00-a7a1-4951-a821-a06f7356fc64)

测试curl:
![image](https://github.com/nelvko/clash-for-linux-install/assets/134823482/118bbfc6-7ee4-4adb-8278-5bfd0f1f65b7)

**Comment by nelvko** [comment]
分流的问题，谷歌走的直连，没走代理，从机场看下有没有配置分流规则

**Comment by wwvvwvwv** [comment]
![image](https://github.com/nelvko/clash-for-linux-install/assets/134823482/33fce2af-f80b-4d47-96c8-d3c46a438435)
我想请问一下为什么ui这里只能选择直连呀，win本地的就可以选择很多节点，另一个ui就根本没反应:(

**Comment by nelvko** [comment]
规则里面有分流规则吗

**Comment by wwvvwvwv** [comment]
> 规则里面有分流规则吗

什么都没有
![image](https://github.com/nelvko/clash-for-linux-install/assets/134823482/7daeb816-2e0e-4071-9a97-6623571042f0)

**Comment by nelvko** [comment]
![image](https://github.com/nelvko/clash-for-linux-install/assets/76961348/527e96da-f028-469d-ac0e-442c4a899f00)
Mode 改为 Global 试试，其实代理已经配置成功了，只是没有分流规则

**Comment by wwvvwvwv** [comment]
奥奥好的，现在完全好了，感谢你!!!!:)
