### ISSUE TITLE
服务启动失败，systemctl status clash日志也不知道哪里有问题

### ISSUE THREAD

**Issue by zhh1137152324** [nelvko/clash-for-linux-install#20]
> [!CAUTION]
>

> 请先提供以下信息
hello, 大佬这是啥问题啊
```shell
# 系统版本信息
ubuntu 20.04 

# 当前所用 shell
bash

```

**描述 & 复现：**
![image](https://github.com/user-attachments/assets/5bb2c53c-2a5c-4a18-8053-b42fe967e83d)
**截图（勿泄露订阅）：**
订阅正常解析了

**Comment by nelvko** [comment]
能正常访问外网吗，试下 `curl -sSL google.com` 有响应吗

**Comment by nelvko** [comment]
你改过脚本代码吗？删除重新执行下一键安装脚本试试

**Comment by zhh1137152324** [comment]
> curl -sSL google.com

![image](https://github.com/user-attachments/assets/1d660bc8-6a16-4fe1-b251-5cd3ede5713e)
能访问但是，但是很奇怪，是个bug吧。

**Comment by zhh1137152324** [comment]
> > curl -sSL google.com
> 
> ![image](https://private-user-images.githubusercontent.com/49141862/398000336-1d660bc8-6a16-4fe1-b251-5cd3ede5713e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4ODg0NDIsIm5iZiI6MTczNDg4ODE0MiwicGF0aCI6Ii80OTE0MTg2Mi8zOTgwMDAzMzYtMWQ2NjBiYzgtNmExNi00ZmUxLWIyNTEtNWNkM2VkZTU3MTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDE3MjIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMmNhMmQwMDllN2JiZWQzMDIxMzk2NDJhMWFhYzI0ZDgwY2MwYzcyZTgyOWViMWNlZTljYjdhZjgwNjZjY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jzLBqVem_yVfqNMwgXxJbdRialMOz1tuzuqyV2O4y3w) 能访问但是，但是很奇怪，是个bug吧。

![image](https://github.com/user-attachments/assets/e736fc62-7987-44a9-b2dd-a9afac892072)
还有一些问题，大佬看看

**Comment by zhh1137152324** [comment]
> 你改过脚本代码吗？删除重新执行下一键安装脚本试试

没改过脚本，只改过配置文件里面7890这个端口和0.0.0.0这个ip地址

**Comment by nelvko** [comment]
更新了下，重新克隆安装试试，（我本地没法复现你的问题。。。
- 每次都需要输入密码：改下配置 `/etc/sudoers`，将 `%sudo   ALL=(ALL:ALL) ALL` 改为 `%sudo   ALL=(ALL:ALL) NOPASSWD: ALL`
- 面板端口：默认监听 `0.0.0.0:9090` 就可以，这样内网和外网ip都可以访问。

**Comment by zhh1137152324** [comment]
> 更新了下，重新克隆安装试试，（我本地没法复现你的问题。。。
> 
> * 每次都需要输入密码：改下配置 `/etc/sudoers`，将 `%sudo   ALL=(ALL:ALL) ALL` 改为 `%sudo   ALL=(ALL:ALL) NOPASSWD: ALL`
> * 面板端口：默认监听 `0.0.0.0:9090` 就可以，这样内网和外网ip都可以访问。

通过ssh端口转发可以在本地通过访问服务器ui界面啦！不过实际上代理启动成功，但是仍然报错这个问题还是存在，我直接把脚本中报错的内容删除了，看着顺眼 hhh     总之感谢！！！
