### ISSUE TITLE
安装好之后 需要在系统开启代理,开启后才能使用

### ISSUE THREAD

**Issue by have999** [nelvko/clash-for-linux-install#21]
ubuntu 24
设置,网络,代理 修改端口号,http https 用一个端口就行;

**Comment by nelvko** [comment]
`clashon` 命令中已经设置系统代理了，如果你是直接`bash`执行的脚本，详见https://github.com/nelvko/clash-for-linux-install?tab=readme-ov-file#bash-clashon-command-not-found
