### ISSUE TITLE
小白提问

### ISSUE THREAD

**Issue by Amamiya23** [nelvko/clash-for-linux-install#4]
clashon
clashui这些命令直接在终端输入应该是没用的把，安装后应该如何配置呢
$ clashui                   
zsh: command not found: clashui

**Comment by nelvko** [comment]
这些命令是通过 bashrc 加载的，基于 bash 终端。
zsh 终端的配置文件是zshrc，执行下列命令后再试下：
 `echo 'source /etc/clash/clashctl.sh' >> ~/.zshrc && source ~/.zshrc`

**Comment by iBongiornor** [comment]
为啥我直接clashon可以但是报没权限，而sudo之后却说bash: command not found: clashon 呢

**Comment by nelvko** [comment]
clashon 是在 root 家目录下的.bashrc 文件中定义的，su 切换到 root 就可以了

**Comment by iBongiornor** [comment]
第一步添加网络地址config没过，所以我就把那段跳过，在user用户下执行的😁

**Comment by nelvko** [comment]
你指的是填机场订阅后没下载下来配置？
是的话脚本会提示解决方法：手动把订阅的配置粘贴到配置文件里。
不要以非 root 用户身份执行脚本，这个脚本仅对root 做了适配，sudo 执行脚本也不行，因为它没有切换到 root 用户

**Comment by iBongiornor** [comment]
我把valid还有检查那段全删了，现在切到root重新安装可以了，但是我现在想sudo执行，这咋办啊，提示找不到命令，如果可以的话，给点修改意见啊
![Uploading Screenshot 2024-08-08 at 2.08.50 PM.png…]()

**Comment by nelvko** [comment]
把源代码 sh 目录下的 clashctl.sh 文件里的代码粘贴（追加）到 .bashrc 文件中
然后执行 `source ~/.bashrc` 或者退出终端重新登录就可以了
