### ISSUE TITLE
小白安装成功但是不知道如何访问外网

### ISSUE THREAD

**Issue by qingchen177** [nelvko/clash-for-linux-install#5]
和无法使用的issue中场景类似
![4d4b25f48558305e8e8cf6bbdb3e21d0](https://github.com/user-attachments/assets/497617cc-48da-4463-b999-55835d8b20bf)

curl -sSL www.google.com 有返回，ping超时。
firefox无法访问google。
![a7e52f6a75acd8e3033b7dc89ec5dc51](https://github.com/user-attachments/assets/e5cab14d-8e74-4a46-86e2-7140955b3364)
yacd和clashui如下：
![b9046aa9af65d3747e89461c9e5ae1f7](https://github.com/user-attachments/assets/dbae0c35-0010-489b-a6a6-fe638a899e04)
![a0e589dba0b420ac1ec71549f115bc3f](https://github.com/user-attachments/assets/9edd3538-fdba-4fc1-8326-02d0dd67c5e1)
。
没linux基础。系统是fedora40。

**Comment by nelvko** [comment]
curl 返回结果说明已经配好代理了，火狐设置里配下代理地址 127.0.0.1:7890

**Comment by qingchen177** [comment]
ok，感谢大佬这么及时响应，配置上就好了！！！

我有个问题想请教一下，我clash设置了global后是意味着我所有的都是从7890端口进出吗？比如我yum install，或者软件商店安装，python下依赖等等，刚入门linux跟着网上配置了一些软件源（flathub这种），没梯子根本下不下来东西。还是说设置了global也要在pycharm（等一系列软件）里面去配置代理才会走7890访问外网。

**Comment by nelvko** [comment]
1. 运行 install 脚本时会设置http_proxy 环境变量，其值就是 127.0.0.1:7890
2. 有些命令发送请求是会读取这个代理变量，有值则走代理。如果不走代理的话大部分命令可以 --help 查看怎么给这个命令设置代理地址
3. 最好还是配置上国内的镜像源，镜像比梯子稳定多了

**Comment by qingchen177** [comment]
ok，感谢佬帮助！祝你多money！！！
