### ISSUE TITLE
docker中的9000端口被PHP占用了.如何修改

### ISSUE THREAD

**Issue by lifetin** [nelvko/clash-for-linux-install#6]
docker中的9000端口被PHP占用了.如何修改

**Comment by nelvko** [comment]
你指的是 web 的 9090 端口吗？

**Comment by lifetin** [comment]
是的呢

**Comment by lifetin** [comment]
![image](https://github.com/user-attachments/assets/5d951758-fe17-4ef9-9c5a-d0c132b02e38)

**Comment by nelvko** [comment]
不冲突啊，web 占用的是 9090 端口，你这个是 9000 端口

**Comment by lifetin** [comment]
![image](https://github.com/user-attachments/assets/21033b17-8c86-46f5-be25-13624c9dd6ed)

打不开呢,
地址2：https://clash.razord.top
这个域名是哪的呀? 
地址2能打开, 但是改不了

**Comment by lifetin** [comment]
![image](https://github.com/user-attachments/assets/a59c9f84-0d2f-4612-8010-b3849b74b12e)
地址2能打开,但是  这个不能修改

**Comment by nelvko** [comment]
看下防火墙有没有放行 9090 端口。
地址2是公用的 web 面板，需要配置上你的 ip 等信息

**Comment by lifetin** [comment]
我这现在是遇到这样的问题
安装好后代理会自动会自动开启,我用
``
curl "https://wwww.baidu.com"
curl: (7) Failed connect to 127.0.0.1:7890; 拒绝连接

```
 clashoff 关闭后,正常curl请求


然后面版,我在局域网访问 http://192.168.0.120:9090/ui  提示
无法访问此网站192.168.0.120 的响应时间过长。

防火墙没有限制,后来彻底关闭了

再重启动安装启动, 好像是服务没有启动成功 
![image](https://github.com/user-attachments/assets/482dc920-3e11-4383-b445-b37ed2efd3a8)

**Comment by nelvko** [comment]
不要直接通过`systemctl`来控制启停，readme文档里有解释。
按照以下步骤再试下：
1. 先执行 `. uninstall.sh`来清理下代理环境，然后再执行`. install.sh`安装。
2. 如果安装过程中订阅链接请求失败，就手动把配置内容复制粘贴到`resource/config.yaml`文件中，然后再执行`. install.sh`
3. 此时应该会安装成功了，代理环境会自动启用，想要关闭代理环境需要使用`clashoff`才能完整关闭。

**Comment by lifetin** [comment]
![image](https://github.com/user-attachments/assets/5dfc2e5b-78be-4175-80a4-61f8939f08e2)

这个是什么问题呢? 
我更新的订阅是一个base64的内容. 获取到了,也写了文件, 但是结果是会提示

错误：下载失败或配置无效！

**Comment by lifetin** [comment]
![image](https://github.com/user-attachments/assets/1b4c4f96-8b79-404b-b6df-659b0abad0b0)
解析的内容是这样的.

**Comment by nelvko** [comment]
这是clash配置文件的参考模板 <https://clash.wiki/configuration/configuration-reference.html>
你这是ss协议格式的且编码了，去机场转换或生成 clash 的订阅链接试试，注意不要编码，需要是满足yaml格式的明文内容。

**Comment by lifetin** [comment]
转换了后 一直有问题,  算了,我直接走export https_proxy=IP  临时也能解决了. 
感谢大哥

**Comment by nelvko** [comment]
已支持本地订阅转换
