### ISSUE TITLE
阿里云部署，无法访问外网

### ISSUE THREAD

**Issue by zhangshaorui** [nelvko/clash-for-linux-install#8]
![clashui](https://github.com/user-attachments/assets/9b0fed11-db08-4fe1-943c-5a35c6e32434)
shang
![阿里云](https://github.com/user-attachments/assets/6c89a3aa-03a0-44a9-a8bb-51fca5ecc3bd)
上面是clashui和阿里云日志，我是想让国内的阿里云，实现外网的功能访问chatgpt，感觉像是配置成功了，但是无法访问外网

**Comment by nelvko** [comment]
试下：运行`clashon`后，再 curl 谷歌，然后截下连接的图（如下，活动/已断开）
![image](https://github.com/user-attachments/assets/7df124c2-ee96-4b2b-8c1e-15d4f5cff8af)

**Comment by zhangshaorui** [comment]
好了，我记得我安装完后，执行过一次clashon，谢谢大佬，可以关闭了

**Comment by nelvko** [comment]
还有就是看下Global里的规则是不是Direct，这个不走代理。最好把配置里的Mode改为Rule，会按规则进行代理
![image](https://github.com/user-attachments/assets/03d27d1e-0f7f-4179-b672-aa5d23680e9f)
