### ISSUE TITLE
Failed to connect to bus: Host is down

### ISSUE THREAD

**Issue by Kevin3777** [nelvko/clash-for-linux-install#9]
![image](https://github.com/user-attachments/assets/05a98a6e-c9c6-46f2-808c-75f90ea1f499)
![image](https://github.com/user-attachments/assets/c39f5b38-f96c-4b22-b26c-51a1e26087ba)
您好，请问这种问题怎么解决？

**Comment by Kevin3777** [comment]
> ![image](https://private-user-images.githubusercontent.com/140407060/381591162-05a98a6e-c9c6-46f2-808c-75f90ea1f499.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTg1NDYsIm5iZiI6MTczMDI5ODI0NiwicGF0aCI6Ii8xNDA0MDcwNjAvMzgxNTkxMTYyLTA1YTk4YTZlLWM5YzYtNDZmMi04MDhjLTc1ZjkwZWExZjQ5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxNDI0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWEyZDY1YjcyYmFkMGY4NDI4MTJkMDE3OWE4ZmMyOTY2N2M1ZjQ4YTk3NDFiOTJmMDgwODJlMTE2MWE3YWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pjyEdXE9QeJP9CboTy0a8peAVqWp4quCuVSsluZfr3k) ![image](https://private-user-images.githubusercontent.com/140407060/381591254-c39f5b38-f96c-4b22-b26c-51a1e26087ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTg1NDYsIm5iZiI6MTczMDI5ODI0NiwicGF0aCI6Ii8xNDA0MDcwNjAvMzgxNTkxMjU0LWMzOWY1YjM4LWY5NmMtNGIyMi1iMjZjLTUxYTFlMjYwODdiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxNDI0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODhlNTNlMjEzMGFlOWRkMGYwYzdkNGRhZjhmNzQ4MDhjODA3NmIzN2U2MTdkOGM3YWE5MmFhZjM0OTNjNmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.09m244wOxUhsURWchl6fS3E_Fv4S3C7svXgOCThCddk) 您好，请问这种问题怎么解决？

不过似乎是成功连上外网了

**Comment by nelvko** [comment]
系统环境是 WSL？谷歌了下应该是系统没兼容好 systemd

**Comment by luozhongze** [comment]
我也是这种，但是我这样的情况没法连上外网
![Uploading 微信图片_20241111205707.png…]()

**Comment by nelvko** [comment]
https://github.com/nelvko/clash-for-linux-install/issues/11#issuecomment-2469817217

**Comment by yu-ci-520** [comment]
<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/6a11eece-297c-40bf-ae89-8305d836872d" />
